name: Run Appium Tests (TestNG + Maven)

on:
  push:
    branches: [ master ]  # or main if you use that branch
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Maven
        uses: s4u/setup-maven-action@v1
        with:
          maven-version: '3.9.6'

      - name: Run Tests via TestNG Suite
        run: mvn clean test -DsuiteXmlFile=run.xml
