name: Run Appium Tests Locally (Self-Hosted)

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start Appium
        run: |
          nohup appium --allow-cors > appium.log 2>&1 &
          sleep 10

      - name: Wait for emulator
        run: |
          adb wait-for-device
          until adb shell getprop sys.boot_completed | grep 1; do
            echo "Waiting for emulator to fully boot..."
            sleep 5
          done
          echo "Emulator is fully booted."

      - name: Run Appium Tests
        working-directory: ${{ github.workspace }}   # Adjust if your pom.xml is not in root
        run: mvn clean test -DsuiteXmlFile=run.xml
