name: Run Appium Tests Locally (Self-Hosted)

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start Appium
        run: |
          nohup appium --allow-cors > appium.log 2>&1 &
          sleep 10

      - name: Wait for emulator
        run: |
          adb wait-for-device
          until adb shell getprop sys.boot_completed | grep 1; do
            echo "Waiting for emulator to fully boot..."
            sleep 5
          done
          echo "Emulator is fully booted."

      - name: Run Appium Tests
        working-directory: ${{ github.workspace }}
        run: mvn clean test -DsuiteXmlFile=run.xml

      - name: Generate Allure Report
        run: |
          npm install -g allure-commandline --force
          allure generate target/allure-results --clean -o target/allure-report

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/allure-report
