name: Run Appium Tests Locally (Self-Hosted)

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Appium Tests
        run: mvn clean test -DsuiteXmlFile=run.xml
